// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	ID         int64     `json:"id"`
	Code       string    `json:"code"`
	ProductID  int64     `json:"product_id"`
	TotalPrice int64     `json:"total_price"`
	CreatedAt  time.Time `json:"created_at"`
}

type Product struct {
	ID        int64        `json:"id"`
	Code      string       `json:"code"`
	Name      string       `json:"name"`
	Price     int64        `json:"price"`
	CreatedAt sql.NullTime `json:"created_at"`
}
